### ISSUE TITLE
[BUG] "wait_for_component()" Error when working with "asyncio.wait()"

### ISSUE THREAD

**Issue by JamesTesting888** [interactions-py/wait_for#3]
The solution is found when I created a thread for this issue, so can you be kind to update?
```
wait_tasks = [
    asyncio.create_task(
        bot.wait_for('on_message_create',
                     check=message_check,
                     timeout=300),
        name="message"),
    asyncio.create_task(
        bot.wait_for_component(
            components=button_actionrow,
            check=component_check,
            timeout=300),
        name="component")
]

done, pending = await asyncio.wait(wait_tasks, return_when=asyncio.FIRST_COMPLETED)
```
<img width="872" alt="Screenshot 2022-03-18 at 19 54 36" src="https://user-images.githubusercontent.com/73999081/159066761-43ff2793-104c-4eff-9f85-b9296a4b6380.png">
<img width="838" alt="Screenshot 2022-03-18 at 19 54 44" src="https://user-images.githubusercontent.com/73999081/159066772-ca05d951-b020-425a-abf4-7c999607023c.png">

**Comment by Catalyst4222** [comment]
Resolved as of 1.0.3
